# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Addison's Blog
email: comments@addisonwebb.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Addison Webb. I am a iOS developer at Ramsey Solutions making
  apps that give hope to people. My passion is making amazing apps and developing
  sustainable business models around those apps. I like to write about my projects
  and experiences so others can learn along with me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://addisonwebb.com" # the base hostname & protocol for your site
twitter_username: addisonwebb
github_username:  addisonwebb

timezone: America/New_York

# Filtering Content
show_drafts: null
future: false
unpublished: false

# Build settings
markdown: kramdown
